arch: amd64
os: linux
dist: focal

language: c++

compiler: gcc

install:
  - sudo apt-get install valgrind

script:
  - mkdir build && cd build
  - cmake ..
  - make clean && make
  - valgrind --tool=memcheck --leak-check=full unit_tests/Google_Tests_run

after_success:
  - bash <(curl -s https://codecov.io/bash)