dist: focal
sudo: required

language: c++
os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - valgrind
      - make
      - cmake
      - lcov

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

script:
  - ls -a
  - cd  unit_tests
  - ls -a
  - git clone https://github.com/google/googletest.git && cd ..
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_CXX_FLAGS="--coverage"
  - cmake --build .
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "${CC_FOR_BUILD}" =~ gcc$ ]]; then valgrind --tool=memcheck --leak-check=yes ./unit_tests/Google_Tests_run; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "${CC_FOR_BUILD}" =~ gcc$ ]]; then lcov --capture --directory . --output-file coverage.info; fi
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "${CC_FOR_BUILD}" =~ gcc$ ]]; then bash <(curl -s https://codecov.io/bash); fi



